[container.image]
repository="wso2"
baseImage="que/runtime:slim"


[settings]
buildImage=true

[[cloud.secret.envs]]
secret_name="music-api-secret"
key_ref="SPOTIFY_CLIENT_ID"
name="BAL_CONFIG_VAR_SPOTIFY_CLIENT_ID"

[[cloud.secret.envs]]
secret_name="music-api-secret"
key_ref="SPOTIFY_CLIENT_SECRET"
name="BAL_CONFIG_VAR_SPOTIFY_CLIENT_SECRET"

[[cloud.secret.envs]]
secret_name="music-api-secret"
key_ref="WEATHER_API_KEY"
name="BAL_CONFIG_VAR_WEATHER_API_KEY" 